In [18]:
import numpy as np
a=np.array([[1,2,3],[2,4,6],[3,6,9]])
a

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [6]:
a.ndim

2

In [7]:
a.shape

(3, 3)

In [8]:
a.size

9

In [9]:
a[2][0]=4

In [10]:
a

array([[1, 2, 3],
       [2, 4, 6],
       [4, 6, 9]])

In [11]:
a[2,2]

9

In [14]:
b=a[0:2,0:2]
b

array([[1, 2],
       [2, 4]])

In [24]:
x=np.array([[1,1,1],[3,6,9],[1,3,9]])
y=np.array([[2,2,2],[2,4,6],[2,4,6]])
z=x-y;
z

array([[-1, -1, -1],
       [ 1,  2,  3],
       [-1, -1,  3]])

In [22]:
a=2*x
a

array([[ 2,  2,  2],
       [ 6, 12, 18],
       [ 2,  6, 18]])

In [23]:
c=np.dot(x,y)
c

array([[ 6, 10, 14],
       [36, 66, 96],
       [26, 50, 74]])

In [25]:
c.T

array([[ 6, 36, 26],
       [10, 66, 50],
       [14, 96, 74]])